### ISSUE TITLE
Most QType constants aren't actually of type QType

### ISSUE THREAD

**Issue by dominikh** [docker/go-p9p#22]
In the following piece of code

```
// Constants for use in Qid to indicate resource type.
const (
	QTDIR    QType = 0x80 // type bit for directories
	QTAPPEND       = 0x40 // type bit for append only files
	QTEXCL         = 0x20 // type bit for exclusive use files
	QTMOUNT        = 0x10 // type bit for mounted channel
	QTAUTH         = 0x08 // type bit for authentication file
	QTTMP          = 0x04 // type bit for not-backed-up file
	QTFILE         = 0x00 // plain file
)
```

only the first constant has type QType. The other constants are untyped/will default to int when used. Constants only "inherit" the previous constant's type if no explicit value is assigned.

**Comment by thaJeztah** [comment]
@dominikh would you be interested in opening a pull request for this?

**Comment by stevvooe** [comment]
Constants actually get type from their context if no type is declared. If the context doesn't define the type, they will default to whatever the default type is for the constant format, which is `int` in this case.

Were you having particular errors during compilation from this or is this just clean up?

**Comment by dominikh** [comment]
@stevvooe That's correct. Which means that code like this:

```
typ := p9p.QTFILE
if someCondition {
  typ = p9p.QTDIR
}
fn(typ)
```

will fail to build. Similarly,  `p9p.QTDIR.String()` will work, while `p9p.QTFILE.String()` will not.

Either all or none of the constants should have a type, anything else is inconsistent.
