### ISSUE TITLE
Errors connecting 9pr to 9ps

### ISSUE THREAD

**Issue by sirnewton01** [docker/go-p9p#26]
I'm using a Mac running macOS 10.11.5 and Go 1.7.1. I compiled both 9ps and 9pr. I launch 9ps first and then 9pr.

I am getting this output from 9pr:
dialing :5640
EOF

From 9ps I get this output:
connected 127.0.0.1:50604
dialing :5640 for &{{0xc42005a0e0}}
connected 127.0.0.1:50605
dialing :5640 for &{{0xc42005a230}}
connected 127.0.0.1:50606
dialing :5640 for &{{0xc420114000}}
connected 127.0.0.1:50607
dialing :5640 for &{{0xc420114150}}
connected 127.0.0.1:50608
dialing :5640 for &{{0xc4201142a0}}
... (for quite some time)
error creating session
error creating session
error creating session
error creating session
error creating session
error creating session
error creating session
error creating session
... (also, for quite some time)

I'm not entirely sure why 9ps is dialing, but I've only just started exploring this project.

**Comment by sirnewton01** [comment]
Oh, I see that the example expects to connect to u9fs. It's probably not running on my system on the port number specified. That's why it is failing.

**Comment by stevvooe** [comment]
@sirnewton01 Let me know if you have further questions!
