### ISSUE TITLE
Setup circleci to use Go 1.7

### ISSUE THREAD

**Issue by stevvooe** [docker/go-p9p#34]
Currently, circleci build is failing due to the use of Go 1.6 in circle ci.

We'll have to upgrade or specifying a build configuration for this to work.

**Comment by Ch3ck** [comment]
@stevvooe Any setups for Go 1.8 too?

**Comment by stevvooe** [comment]
@Ch3ck Moving away from circle but I've added 1.8 and tip to the travis build.
